config/routes.rb
Rails.application.routes.draw do
  
  get '/dashboard', to: 'users#dashboard'
  post 'users/edit', to: 'users#update'

  resources :pets do
    member do
      delete :delete_pet_photos
      post :upload_pet_photos
    end
  end

  root 'pages#home'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout', edit: 'profile' }, 
              controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :costs
  has_many_attached :pet_photos
  accepts_nested_attributes_for :costs
  has_rich_text :pet_description

  geocoded_by :address
  after_validation :geocode, if: :address_changed? 

  
  # Validations Start Here
  attr_accessor :validates_step

  with_options if: :validates_step_1? do |x|
    x.validates :weight, numericality: { 
      only_integer: true,
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: 150,
      message: " Can not be more than 150 KG and no less than 0 KG"
    }, on: :update
    x.validates :age, numericality: { 
      only_integer: true,
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: 40,
      message: " Can not be older than 40 years old and no younger than 0 years"
    }, on: :update

    x.validates :pet_description, length: { 
      minimum: 150, 
      maximum: 3000,
      message: " Please put a meaningful descriptipn of the pet, at least 150 characters and no more than 3000"
    }
    x.validates :michrochip, format: {
      with: /^\w+$/i,
      multiline: true,
      message: " can only contain letters and numbers"},
      length: {
        minimum: 10,
        maximum: 100
      }, allow_blank: true, on: :update
  end

  with_options if: :validates_step_3? do |x|
    x.validates :pet_photos, presence: true
  end

  private

    def validates_step_1?
      self.validates_step == 1
    end

    def validates_step_2?
      self.validates_step == 2
    end

    def validates_step_3?
      self.validates_step == 3
    end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  protect_from_forgery except: [:upload_pet_photos]

  before_action :authenticate_user!, except: [:show]
  before_action :set_pet, except: [:new, :create]
  before_action :not_auth, only: [:update, :edit, :upload_pet_photos, :delete_pet_photos]
  before_action :set_step, only: [:update, :edit]

 # Instantiate is get method - it just gets the information of the fields. Get get ready!
  def new
    @pet = current_user.pets.build
    @categories = Category.all
  end

  # Creating is a Post method it literally save into the fields of the database.
  def create
    @pet = current_user.pets.build(pet_params)
    if @pet.save
      @pet.costs.create(Cost.cost_types.values.map { |i| {cost_type: i} })
      redirect_to edit_pet_path(@pet, step: 1), notice: "Great please continue filling out the remaining fileds"
    else
      flash[:alert] = "Ooops something does not seems right."
      render :new
    end
  end

  def edit
    @categories = Category.all
  end


  def update

    if @step == 1
     @pet.validates_step = 1
    end

    if @step == 2
      pet_params[:costs_attributes].each do |k, v|
        if @pet.has_one_transport_cost && v[:cost_type] != Cost.cost_types.key(0)
          flash[:notice] = "Great...saved!"
        else
          if v[:title].blank? || v[:description].blank? || v[:transport_time].blank? || v[:cost].blank?
            return redirect_to request.referer, flash: {error: "Please continue to fill out all transporation fields. They are required."}
          end
        end
      end
    end

    if @step == 3
      @pet.validates_step = 3
    end

    if @step == 4
      #Add variable to trigger validation in model
    end
    
    if @pet.update(pet_params)
      flash[:notice] = "Saved successfully."
    else
      redirect_to request.referrer, flash: { error: @pet.errors.full_messages } and return
    end

    # Add Logic to make sure when user clicks save and conitinue, we increment @step by +1
    if @step < 4
      redirect_to edit_pet_path(@pet, step: @step + 1)
    else
      redirect_to dashboard_path
    end


  end


  def show
  end

  def upload_pet_photos
    @pet.pet_photos.attach(params[:file])
    render json: {success: true}
  end

  def delete_pet_photos
    @img = ActiveStorage::Attachment.find(params[:pet_photo_id])
    @img.purge
    redirect_to edit_pet_path(@pet), notice: 'Removed successfully.'
  end

  

  private
    def set_step
      @step = params[:step].to_i > 0 ? params[:step].to_i : 1
    end
    def set_pet
      @pet = Pet.find(params[:id])
    end

    def not_auth
      redirect_to root_path alert: "I don't think you have perrmision to do this" unless current_user.id == @pet.user_id
    end
    def pet_params
      params.require(:pet).permit(:title, :pet_description, :active, :is_spayed, :has_one_transport_cost, :video, :category_id,
                                  :is_dog_friendly, :is_cat_friendly, :is_people_friendly, :is_dominant, :is_shows_past_abuse, 
                                  :is_barks_alot, :weight, :age, :michrochip, :address, costs_attributes: [:id, :title, :description, 
                                  :transport_time, :cost, :cost_type])
    end
end

app/helpers/pets_helper.rb
module PetsHelper
  def video_embed(video_url)

    # REGEX EXTRACT ID
    regex_id = /(?:youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/|vimeo\.com\/)([a-zA-Z0-9_-]{8,11})/
    match_id = regex_id.match(video_url)
    video_id = ""
    if match_id && !match_id[1].blank?
      video_id = match_id[1]
    end

    # REGEX EXTRACT PROVIDER
    regex_prov = /(youtube|youtu\.be|vimeo)/
    match_prov = regex_prov.match(video_url)
    video_prov = ""
    if match_prov && !match_prov[1].blank?
      video_prov = case match_prov[1]
                     when "youtube"
                       :youtube
                     when "youtu.be"
                       :youtube
                     when "vimeo"
                       :vimeo
      end
    end

    case video_prov
      when :youtube
        "https://www.youtube.com/embed/#{video_id}"
      when :vimeo
        "https://player.vimeo.com/video/#{video_id}"
    end

  end
end

app/views/pets/_step1.html.erb
<div class="<%= 'd-none' unless @step == 1 %>">
  <p class="subtitle text-primary">
    Please continue to fill out the fields
  </p>
  <h1 class="h2">Pet Details</h1>

  <!-- Form  -->
  <div class="form-group">
    <label>Pet's Name</label>
    <%= f.text_field :title, autocomplete: 'title', class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Pet's Category</label>
    <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id]}, selected: @pet.category_id), { wraper: {} }, { class: 'custom-select mb-3'}) %>
  </div>

  <div class="row">
    <div class="col-lg-4 col-md-6 col-12">
      <div class="form-group ">
        <%= f.check_box :is_dog_friendly, class: 'myclass1 ml-1 mt-2' %>
        <%= f.label :is_dog_friendly, class: 'myclass1 ml-1' do %>
          Friendly with dogs
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 col-12">
      <div class="form-group ">
        <%= f.check_box :is_cat_friendly, class: 'myclass1 ml-1 mt-2' %>
        <%= f.label :is_cat_friendly, class: 'myclass1 ml-1' do %>
          Friendly with cats
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 col-12">
      <div class="form-group ">
        <%= f.check_box :is_dominant, class: 'myclass1 ml-1 mt-2' %>
        <%= f.label :is_dominant, class: 'myclass1 ml-1' do %>
          Dominant alpha male/female
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 col-12">
      <div class="form-group ">
        <%= f.check_box :is_people_friendly, class: 'myclass1 ml-1 mt-2' %>
        <%= f.label :is_people_friendly, class: 'myclass1 ml-1' do %>
          Friendly with strangers
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 col-12">
      <div class="form-group ">
        <%= f.check_box :is_shows_past_abuse, class: 'myclass1 ml-1 mt-2' %>
        <%= f.label :is_shows_past_abuse, class: 'myclass1 ml-1' do %>
          Clear signs of abused past
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 col-12">
      <div class="form-group ">
        <%= f.check_box :is_barks_alot, class: 'myclass1 ml-1 mt-2' %>
        <%= f.label :is_barks_alot, class: 'myclass1 ml-1' do %>
          This dog barks a lot
        <% end %>
      </div>
    </div>
  </div>


  <div class="row py-4">
    <div class="col-md-6 col-lg-4">
      <div class="form-group">
        <label>Pet Age</label>
        <%= f.number_field :age, placeholder: 'Enter age', class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-6 col-lg-4">
      <div class="form-group">
        <label>Pet Weight / Kg</label>
        <%= f.number_field :weight, placeholder: 'Enter weight In KG', class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-6 col-lg-4">
      <div class="form-group">
        <label>Microchip Number (If Microchiped)</label>
        <%= f.text_field :michrochip, placeholder: 'Microchip Number', class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label>Pet Address</label>
    <%= f.text_field :address, class: 'form-control' %>
    <small class="form-text text-muted">Hey this is location of your pet.</small>
  </div>

  <div class="form-group">
    <label>Pet Description</label>
    <%= f.rich_text_area :pet_description, class: 'form-control', rows: '20' %>
    <small class="form-text text-muted">Tell your user what you need them to write about. Tell your user what you need them to write about</small>
  </div>

  <div class="form-group ">
    <%= f.check_box :is_spayed, class: 'myclass1 ml-1 mt-2' %>
    <%= f.label :is_spayed, class: 'myclass1' do %>
      Spayed / Neutered
    <% end %>
    <small class="form-text text-muted">Neutered or Spayed if the dog has been fixed, canot reproduce. Check this box.</small>
  </div>

  <!-- Has One Transport Cost Check Box -->
  <div id="transport-cost" class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Important</h4>
    <p>Please indicate the costs associated with this pet. There is always a cost, primarly most costs are associated with transporation. This is why we've createtd 3 main transportation costs. They are Local, National and International. You must check this boxif you only want your pet to be adoted localy within your neighbourhood or anywhere close to you.</p>
    <hr>
    <p class="mb-4">If you are not sure of the associated costs in transporting your pet by or to far away places, you can check the box for now to indicate local delivery only and fill out the local fields. You must have at least one cost associated with the pet.</p>
    <div class="row">
      <div class="col-md-6 col-md-4 col-sm-12">
        <div class="form-group ">
          <%= f.select(:has_one_transport_cost, options_for_select([["I have multiple transportation costs", false],["I have only one transportation cost", true]], selected: @pet.has_one_transport_cost), { wrapper: {} }, { class: 'custom-select' }) %>
        </div>
      </div>
    </div>
  </div>

  <div class="ml-auto float-right mr-2 mt-3">
    <%= f.submit "Save & Contiunue", class: 'btn btn-primary' %>
  </div>
</div>

app/views/pets/_step2.html.erb
<div class="<%= 'd-none' unless @step == 2 %>">
  <p class="subtitle text-primary">
    Pet Transportation Costs
  </p>
  <h1 class="h2 mb-5">Pet Costs</h1>
  <div class="row form-group">

    <div class="col-md-12">
      <div class="form-group">
        <div class="alert alert-warning">
          <% if !@pet.has_one_transport_cost %>
            Hey <%= current_user.fullname  %> If you ONLY want one transportation cost for local delivery within your neighbourhood, you need to select  
            <br>
            <strong>
              <%= link_to '"I have only one transportation cost - In Previous Step Here"', edit_pet_path(@pet, anchor: "transport-cost", step: 1) %>
            </strong>

          <% else %>
            Hey <%= current_user.fullname  %> If you want add many transportation costs for local delivery, national, and International you need to select
            <br>
            <strong>
              <%= link_to '"I have multiple transportation costs - In Previous Step Here"', edit_pet_path(@pet, anchor: "transport-cost", step: 1) %>
            </strong>
          <% end %>
        </div>
      </div>
    </div>

    <%= f.fields_for :costs, @pet.costs.order(:cost_type) do |c| %>
      <div class="col-lg-4 <%= 'my-hidden' if @pet.has_one_transport_cost && !c.object.local?  %>">
        <%= c.hidden_field :cost_type %>

        <div class="card border-primary mb-3">
          <div class="card-header bg-transparent border-primary">
            <h6 class="mb-0"><%= c.object.cost_type.capitalize %></h6>
          </div>
          <div class="card-body text-muted">
            <div class="form-group">
              <label for="">Name of cost</label>
              <%= c.text_field :title, placeholder: c.object.cost_type.capitalize, class: 'form-control text-primary' %>
            </div>
            <div class="form-group">
              <label for="">Describe the <%= c.object.cost_type.capitalize %> transportation to the best of your ability</label>
              <%= c.text_area :description, placeholder: 'Description', rows: '5', class: 'form-control text-primary' %>
            </div>
          </div>
          <div class="card-footer bg-transparent border-muted">
            <div class="form-group">
              <div class="input-group mb-2">
                <div class="input-group-prepend">
                  <div class="input-group-text">Days</div>
                </div>
                <%= c.number_field :transport_time, placeholder: 'Pet delivery time', class: 'form-control text-primary' %>
              </div>
            </div>
          </div>
          <div class="card-footer bg-transparent border-muted">
            <div class="form-group">
              <div class="input-group mb-2">
                <div class="input-group-prepend">
                  <div class="input-group-text">Cost</div>
                </div>
                <%= c.number_field :cost, placeholder: 'Total cost', class: 'form-control text-primary' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="ml-auto float-right mr-2 mt-3">
    <%= f.submit "Save & Contiunue", class: 'btn btn-primary' %>
  </div>
</div>

app/views/pets/_step3.html.erb
<div class="<%= 'd-none' unless @step == 3 %>">
  <!-- Photo Uplaod Box from Dropzone.js-->
  <div class="form-group">
    <label>Pet Youtube URL</label>
    <%= f.text_field :video, autocomplete: 'video', class: 'form-control' %>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="dropzone" action="/pets/<%= @pet.id %>/upload_pet_photos" id="petDropzone">
        <div class="dz-message d-flex flex-column">
          <i class="material-icons text-primary">cloud_upload</i>
          Drag & Drop Or Click here to upload photos
        </div>
      </div>
    </div>
  </div>
  <!-- List all photos goes here-->
  <div class="row p-3">
    <% @pet.pet_photos.each do |photo| %>
      <div class="col-lg-4 p-1">
        <%= image_tag url_for(photo), class: 'pet-image' %>
        <div class="card-image-overlay-bottom">
          <%= link_to delete_pet_photos_pet_url(pet_photo_id: photo.id, id: @pet.id), method: :delete, data: {confirm: "Are you Sure!", class: 'pet-delete'} do %>
            <div class="pet-delete">Delete</div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="ml-auto float-right mr-2 mt-3">
    <%= f.submit "Save & Contiunue", class: 'btn btn-primary' %>
  </div>


  <script>
    Dropzone.options.petDropzone = {
      paramName: "file", // The name that will be used to transfer the file
      maxFilesize: 2, // MB
      acceptedfFiles: 'image/*',
      init: function() {
        this.on('complete', function (file) {
          location.reload();
        })
      }
    };
  </script>
</div>

app/views/pets/_step4.html.erb
<div class="<%= 'd-none' unless @step == 4 %>">
  <div class="ml-auto float-right mr-2 mt-3">
    <%= f.submit "Publish Pet", class: 'btn btn-primary' %>
  </div>
</div>

app/views/pets/_steps_menu.html.erb
<div class="scrollable-wrapper">
  <div class="col bg-white border rounded mr-2 scrollable-item <%= @step == 1 ? 'border-primary shadow-sm' : 'border-light shadow-none' %>">
    <%= link_to edit_pet_path(@pet, step: 1), class: 'd-block my-2 text-decoration-none' do %>
      <span class="text-primary">Step 1 - Pet Details</span>
      <br>
      <span class="font-weight-bold text-muted">Completed</span>
      <i class="fa fa-check float-right text-muted"></i>
    <% end %>
  </div>
  <div class="col bg-white border rounded mr-2 scrollable-item <%= @step == 2 ? 'border-primary shadow-sm' : 'border-light shadow-none' %>">
    <%= link_to edit_pet_path(@pet, step: 2), class: 'd-block my-2 text-decoration-none' do %>
      <span class="text-primary">Step 2 - Pet Transportation</span>
      <br>
      <span class="font-weight-bold text-muted">Completed</span>
      <i class="fa fa-check float-right text-muted"></i>
    <% end %>
  </div>
  <div class="col bg-white border rounded mr-2 scrollable-item <%= @step == 3 ? 'border-primary shadow-sm' : 'border-light shadow-none' %>">
    <%= link_to edit_pet_path(@pet, step: 3), class: 'd-block my-2 text-decoration-none' do %>
      <span class="text-primary">Step 3 - Pet Media</span>
      <br>
      <span class="font-weight-bold text-muted">Completed</span>
      <i class="fa fa-check float-right text-muted"></i>
    <% end %>
  </div>
  <div class="col bg-white border rounded mr-2 scrollable-item <%= @step == 4 ? 'border-primary shadow-sm' : 'border-light shadow-none' %>">
    <%= link_to edit_pet_path(@pet, step: 4), class: 'd-block my-2 text-decoration-none' do %>
      <span class="text-primary">Step 4 - Publish</span>
      <br>
      <span class="font-weight-bold text-muted">Completed</span>
      <i class="fa fa-check float-right text-muted"></i>
    <% end %>
  </div>
</div>

app/views/pets/create.html.erb
<h1>Pets#create</h1>
<p>Find me in app/views/pets/create.html.erb</p>

app/views/pets/edit.html.erb
<section class="py-4">
  <div class="container">
    <%= render 'steps_menu' %>

    <%= form_for @pet do |f| %>

      <%= hidden_field_tag 'step', @step %>

      <%= render 'step1', f:f %>
      <%= render 'step2', f:f %>
      <%= render 'step3', f:f %>
      <%= render 'step4', f:f %>

    <% end %>


  </div>
</section>

app/views/pets/new.html.erb
<section class="py-4">
  <div class="container">
    <div class="row">
      <!-- Left Column -->
      <div class="col-lg-5">
        <p class="subtitle mb-3">Add a pet for adoption</p>
        <h1 class="hello mb-3">Let's Do this</h1>
        <div>
          <p class="text-muted">shdjshfmgshdhh smdgshmfdg bsahmdfbmsb shdjshfmgshdhh smdgshmfdg bsahmdfbmsbshdjshfmgshdhh smdgshmfdg bsahmdfbmsbshdjshfmgshdhh smdgshmfdg bsahmdfbmsbshdjshfmgshdhh smdgshmfdg bsahmdfbmsb </p>
          
        </div>
      </div>
      <!-- RIght Column -->
      <div class="col-lg-7">
        <div class="form-group-row">
          <div class="mr-auto ml-auto align-items-center col-lg-8">
            <%= form_for @pet do |f| %>

              <div class="form-group">
                <label>Pet Name</label>
                <%= f.text_field :title, autocomplete: 'title', class: 'form-control', required: 'true' %>
              </div>

              <div class="form-group">
                <label>Choose Category</label>
                <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id]}), { wraper: {} }, { class: 'custom-select mb-3'}) %>
              </div>



              <%= f.submit 'Save & Continue', class: 'btn btn-primary mt-3' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pets/show.html.erb
<section>


  <div class="carousel" data-flickity='{ "wrapAround": true }' style="margin-top: -50px;">
    <% @pet.pet_photos.each do |photo| %>
      <%= image_tag url_for(photo), class: 'carousel-cell' %>
    <% end %>
  </div>

  <div class="container py-5">
    <div class="row">
      <!-- Left Column-->
      <div class="col-lg-8">
        <!-- Location titiel About -->
        <div class="tex-block">
          <p class="text-primary">
          <i class="fa fa-map-marker-alt mr-1"></i>
            Montreal Canada
          </p>
          <h1><%= @pet.title %></h1>
          <ul class="list-inline text-sm mb-4">
            <li class="list-inline-item mr-3 mb-2">
              <span class="text-secondary">Breed:</span>
              Mix
            </li>
            <li class="list-inline-item mr-3 mb-2">
              <span class="text-secondary">Age:</span>
              <%= pluralize(@pet.age, 'Year') %> 
            </li>
            <li class="list-inline-item mr-3 mb-2">
              <span class="text-secondary">Sex:</span>
              Female
            </li>
            <li class="list-inline-item mr-3 mb-2">
              <span class="text-secondary">Weight:</span>
              <%= @pet.weight %> Kg
            </li>
            <li class="list-inline-item mr-3 mb-2">
              <i class="<%= @pet.michrochip? ? 'fa fa-check text-primary' : 'fa fa-times text-danger' %> mr-1 "></i>
              Microchiped
            </li>
            <li class="list-inline-item mr-3 mb-2">
              <i class="<%= @pet.is_spayed ? 'fa fa-check text-primary' : 'fa fa-times text-danger' %> mr-1"></i>
              Spayed
            </li>
          </ul>
          <h4 class="mb-3">About</h4>
          <p><%= @pet.pet_description %></p>
        </div>
        <!-- Video -->
        <div class="text-block">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="<%= video_embed(@pet.video) %>" allowfullscreen></iframe>
          </div>
        </div>

        <!-- Location Map -->
        <div class="text-block">
          <h4 class="mb-4">Pet Location</h4>
          <div class="map-wrapper" style="height: 350px;">

            <div id="map" style="height: 325px;"></div>

            <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<% Rails.application.credentials.dig(:googlemaps, :GOOGLE_MAP_APP_KEY) %>&libraries=places">
            </script>

            <script>
              function initialize() {
                var location = {lat: <%= @pet.latitude %>, lng: <%= @pet.longitude %>}
                var map = new google.maps.Map(document.getElementById('map'), {
                  center: location,
                  zoom: 14
                });

                var marker = new google.maps.Marker({
                  position: location,
                  map: map
                });

                var infoWindow = new google.maps.InfoWindow({
                  content: '<div class"content"><%= image_tag missing_pet_img(@pet), style: 'width: 135px;' %></div>'
                });

                infoWindow.open(map, marker);

              }

              google.maps.event.addDomListener(window, 'load', initialize);
              
            </script>


          </div>
        </div>

        <!-- Vaccinations & Microchip -->
        <div class="text-block">
          <h4 class="mb-4">Vaccinations & Microchip</h4>
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled text-muted">
                <li class="mb-2">
                  <i class="text-center text-secondary fa fa-check mr-3"></i>
                  Rabies A
                </li>
                <li class="mb-2">
                  <i class="text-center text-secondary fa fa-check mr-3"></i>
                  Rabies A
                </li>
                <li class="mb-2">
                  <i class="text-center text-primary fa fa-check mr-3"></i>
                  Rabies A
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled text-muted">
                <li class="mb-2">
                  <i class="text-center text-success fa fa-check mr-3"></i>
                  Rabies A
                </li>
                <li class="mb-2">
                  <i class="text-center text-success fa fa-check mr-3"></i>
                  Rabies A
                </li>
                <li class="mb-2">
                  <i class="text-center tex-secondary fa fa-check mr-3"></i>
                  Rabies A
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Addiotional Info -->
        <div class="text-block">
          <h4 class="mb-3">Additional Info</h4>
          <ul class="list-inline">
          <% if @pet.is_dog_friendly %>
            <li class="list-inline-item mb-2">
              <span class="badge badge-pill badge-light p-3 text-muted">Dog friendly</span>
            </li>
          <% end %>

          <% if @pet.is_cat_friendly %>
            <li class="list-inline-item mb-2">
              <span class="badge badge-pill badge-light p-3 text-muted">Cat friendly</span>
            </li>
          <% end %>
          <% if @pet.is_dominant %>
            <li class="list-inline-item mb-2">
              <span class="badge badge-pill badge-light p-3 text-muted">Dominant</span>
            </li>
          <% end %>
          <% if @pet.is_shows_past_abuse %>
            <li class="list-inline-item mb-2">
              <span class="badge badge-pill badge-light p-3 text-muted">Shows signs of post abuse</span>
            </li>
          <% end %>
          <% if @pet.is_people_friendly %>
            <li class="list-inline-item mb-2">
              <span class="badge badge-pill badge-light p-3 text-muted">Friendly with people</span>
            </li>
          <% end %>
       
          </ul>
        </div>
        <!-- About the owner of pet -->
        <div class="text-block">
          <div class="media">
            <%= image_tag avatar_url(@pet.user), class: 'avatar-show mr-4' %>
            <div class="media-body">
              <p>
                <span class="text-muted text-uppercase text-sm">Pet Founder</span>
                <br>
                <strong>
                  <%= @pet.user.organization.blank? ? @pet.user.fullname : @pet.user.organization %>
                </strong>
              </p>
              <p class="text-sm"><%= @pet.user.about %></p>

              <p>
                <% if @pet.user.pets.count > 1 %>
                  <a href="">
                   See <%= @pet.user.fullname %>'s <%= @pet.user.pets.count %> other pets for adoption
                    <i class="fa fa-long-arrow-alt-right ml-2"></i>
                  </a>
                <% end %>
              </p>
              
            </div>
          </div>
        </div>
      </div>
      <!-- RIght Column-->
      <div class="col-lg-4">
        <div class="shadow p-4 ml-lg-3">
          <h6 class="p-1"><%= @pet.user.organization.blank? ? @pet.user.fullname : @pet.user.organization %></h6>
          <button class="btn btn-block btn-primary">Adopt Me</button>
          <hr>
          <p class="text-muted text-sm p-1">Share this</p>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/pets/update.html.erb
<h1>Pets#update</h1>
<p>Find me in app/views/pets/update.html.erb</p>